### ISSUE TITLE
Draft Status

### ISSUE THREAD

**Issue by zaabi1995** [alyf-de/pdf_on_submit#8]
Dear, thank you for your support, i have noticed that when a pdf is created, it is always created on a draft status, is this intentional?

**Comment by barredterra** [comment]
Hi @zaabi1995, this is due to the fact that the `on_submit` hook is executed while the document is still in draft. There is no `after_submit` hook yet ([available hooks](https://frappeframework.com/docs/v13/user/en/basics/doctypes/controllers#controller-hooks)). A workaround is to disable the "DRAFT" notice altogether, via print settings.

Closing this as it cannot be fixed, currently.
